CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'Subscriber' CHECK (role IN ('SuperAdmin', 'Admin', 'Subscriber')),
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modifiedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
